
package com.qycloud.taiyuan.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-14T10:30:06.385+08:00
 * Generated source version: 3.0.0
 * 
 */
 
public class QueryInformationSvcPortType_QueryInformationSvcPort_Server{

    protected QueryInformationSvcPortType_QueryInformationSvcPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new queryInformationSvcPortImpl();
        String address = "http://localhost:8080/server/services/queryInformationSvc.queryInformationSvcPort/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new QueryInformationSvcPortType_QueryInformationSvcPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
