package com.qycloud.taiyuan.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-14T10:30:06.377+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://rockontrol.com/oup/service/QueryInformationSvc", name = "queryInformationSvcPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface QueryInformationSvcPortType {

    /**
     * 鏍规嵁绯荤粺鍚嶆煡璇㈢粍缁囨満鏋勪俊鎭�
     */
    @WebResult(name = "return", targetNamespace = "http://oup.rockontrol.com")
    @Action(input = "urn:queryOrgsBySysname", output = "http://rockontrol.com/oup/service/QueryInformationSvc/QueryInformationSvcPortType/queryOrgsBySysnameResponse")
    @RequestWrapper(localName = "queryOrgsBySysname", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryOrgsBySysname")
    @WebMethod(action = "urn:queryOrgsBySysname")
    @ResponseWrapper(localName = "queryOrgsBySysnameResponse", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryOrgsBySysnameResponse")
    public java.lang.String queryOrgsBySysname(
        @WebParam(name = "sysName", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String sysName
    );

    /**
     * 鏍规嵁绯荤粺鍚嶆煡璇㈠矖浣嶅強鐢ㄦ埛淇℃伅
     */
    @WebResult(name = "return", targetNamespace = "http://oup.rockontrol.com")
    @Action(input = "urn:queryJobUserBySysname", output = "http://rockontrol.com/oup/service/QueryInformationSvc/QueryInformationSvcPortType/queryJobUserBySysnameResponse")
    @RequestWrapper(localName = "queryJobUserBySysname", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryJobUserBySysname")
    @WebMethod(action = "urn:queryJobUserBySysname")
    @ResponseWrapper(localName = "queryJobUserBySysnameResponse", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryJobUserBySysnameResponse")
    public java.lang.String queryJobUserBySysname(
        @WebParam(name = "sysName", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String sysName
    );

    /**
     * 鏍规嵁缁勭粐鏈烘瀯ID鏌ヨ涓�潯缁勭粐鏈烘瀯淇℃伅
     */
    @WebResult(name = "return", targetNamespace = "http://oup.rockontrol.com")
    @Action(input = "urn:queryTheOrg", output = "http://rockontrol.com/oup/service/QueryInformationSvc/QueryInformationSvcPortType/queryTheOrgResponse")
    @RequestWrapper(localName = "queryTheOrg", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryTheOrg")
    @WebMethod(action = "urn:queryTheOrg")
    @ResponseWrapper(localName = "queryTheOrgResponse", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryTheOrgResponse")
    public java.lang.String queryTheOrg(
        @WebParam(name = "sysName", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String sysName,
        @WebParam(name = "oid", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String oid
    );

    /**
     * 淇敼鐢ㄦ埛瀵嗙爜
     */
    @WebResult(name = "return", targetNamespace = "http://oup.rockontrol.com")
    @Action(input = "urn:updateUserPwd", output = "http://rockontrol.com/oup/service/QueryInformationSvc/QueryInformationSvcPortType/updateUserPwdResponse")
    @RequestWrapper(localName = "updateUserPwd", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.UpdateUserPwd")
    @WebMethod(action = "urn:updateUserPwd")
    @ResponseWrapper(localName = "updateUserPwdResponse", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.UpdateUserPwdResponse")
    public java.lang.Boolean updateUserPwd(
        @WebParam(name = "jsonStr", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String jsonStr
    );

    /**
     * 鏍规嵁缁勭粐鏈烘瀯鍚嶇О鏌ヨ閮ㄩ棬鍙婂叾瀛愰儴闂ㄤ俊鎭�
     */
    @WebResult(name = "return", targetNamespace = "http://oup.rockontrol.com")
    @Action(input = "urn:queryOrgs", output = "http://rockontrol.com/oup/service/QueryInformationSvc/QueryInformationSvcPortType/queryOrgsResponse")
    @RequestWrapper(localName = "queryOrgs", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryOrgs")
    @WebMethod(action = "urn:queryOrgs")
    @ResponseWrapper(localName = "queryOrgsResponse", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryOrgsResponse")
    public java.lang.String queryOrgs(
        @WebParam(name = "oid", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String oid
    );

    /**
     * 鏍规嵁 缁勭粐鏈烘瀯鍚嶇О鏌ヨ鐢ㄦ埛淇℃伅
     */
    @WebResult(name = "return", targetNamespace = "http://oup.rockontrol.com")
    @Action(input = "urn:queryUsers", output = "http://rockontrol.com/oup/service/QueryInformationSvc/QueryInformationSvcPortType/queryUsersResponse")
    @RequestWrapper(localName = "queryUsers", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryUsers")
    @WebMethod(action = "urn:queryUsers")
    @ResponseWrapper(localName = "queryUsersResponse", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryUsersResponse")
    public java.lang.String queryUsers(
        @WebParam(name = "oid", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String oid
    );

    /**
     * 鏍规嵁鏀垮姟鍙疯幏寰椾竴鏉＄敤鎴蜂俊鎭�
     */
    @WebResult(name = "return", targetNamespace = "http://oup.rockontrol.com")
    @Action(input = "urn:queryTheUser", output = "http://rockontrol.com/oup/service/QueryInformationSvc/QueryInformationSvcPortType/queryTheUserResponse")
    @RequestWrapper(localName = "queryTheUser", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryTheUser")
    @WebMethod(action = "urn:queryTheUser")
    @ResponseWrapper(localName = "queryTheUserResponse", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryTheUserResponse")
    public java.lang.String queryTheUser(
        @WebParam(name = "sysName", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String sysName,
        @WebParam(name = "loginName", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String loginName
    );

    /**
     * 鏍规嵁绯荤粺鍚嶆煡璇㈢敤鎴蜂俊鎭�
     */
    @WebResult(name = "return", targetNamespace = "http://oup.rockontrol.com")
    @Action(input = "urn:queryUsersBySysname", output = "http://rockontrol.com/oup/service/QueryInformationSvc/QueryInformationSvcPortType/queryUsersBySysnameResponse")
    @RequestWrapper(localName = "queryUsersBySysname", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryUsersBySysname")
    @WebMethod(action = "urn:queryUsersBySysname")
    @ResponseWrapper(localName = "queryUsersBySysnameResponse", targetNamespace = "http://oup.rockontrol.com", className = "com.qycloud.taiyuan.ws.QueryUsersBySysnameResponse")
    public java.lang.String queryUsersBySysname(
        @WebParam(name = "sysName", targetNamespace = "http://oup.rockontrol.com")
        java.lang.String sysName
    );
}
