package com.qycloud.taiyuan.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-14T10:30:06.390+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "queryInformationSvc", 
                 // wsdlLocation = "file:/d:/tmp/queryInformationSvc.wsdl",
                  targetNamespace = "http://rockontrol.com/oup/service/QueryInformationSvc") 
public class QueryInformationSvc extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rockontrol.com/oup/service/QueryInformationSvc", "queryInformationSvc");
    public final static QName QueryInformationSvcPort = new QName("http://rockontrol.com/oup/service/QueryInformationSvc", "queryInformationSvcPort");
    static {
    	String addr = "http://localhost:8080/server/services/queryInformationSvc.queryInformationSvcPort/?wsdl";
        URL url = null;
        try {
            url = new URL(addr);
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QueryInformationSvc.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/d:/tmp/queryInformationSvc.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QueryInformationSvc(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QueryInformationSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryInformationSvc() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryInformationSvc(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryInformationSvc(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public QueryInformationSvc(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns QueryInformationSvcPortType
     */
    @WebEndpoint(name = "queryInformationSvcPort")
    public QueryInformationSvcPortType getQueryInformationSvcPort() {
        return super.getPort(QueryInformationSvcPort, QueryInformationSvcPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryInformationSvcPortType
     */
    @WebEndpoint(name = "queryInformationSvcPort")
    public QueryInformationSvcPortType getQueryInformationSvcPort(WebServiceFeature... features) {
        return super.getPort(QueryInformationSvcPort, QueryInformationSvcPortType.class, features);
    }

}
