
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.qycloud.taiyuan.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-14T10:30:06.361+08:00
 * Generated source version: 3.0.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "queryInformationSvc",
                      portName = "queryInformationSvcPort",
                      targetNamespace = "http://rockontrol.com/oup/service/QueryInformationSvc",
                     // wsdlLocation = "file:/d:/tmp/queryInformationSvc.wsdl",
                      endpointInterface = "com.qycloud.taiyuan.ws.QueryInformationSvcPortType")
                      
public class queryInformationSvcPortImpl implements QueryInformationSvcPortType {

    private static final Logger LOG = Logger.getLogger(queryInformationSvcPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.qycloud.taiyuan.ws.QueryInformationSvcPortType#queryOrgsBySysname(java.lang.String  sysName )*
     */
    public java.lang.String queryOrgsBySysname(java.lang.String sysName) { 
        LOG.info("Executing operation queryOrgsBySysname");
        System.out.println(sysName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.qycloud.taiyuan.ws.QueryInformationSvcPortType#queryJobUserBySysname(java.lang.String  sysName )*
     */
    public java.lang.String queryJobUserBySysname(java.lang.String sysName) { 
        LOG.info("Executing operation queryJobUserBySysname");
        System.out.println(sysName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.qycloud.taiyuan.ws.QueryInformationSvcPortType#queryTheOrg(java.lang.String  sysName ,)java.lang.String  oid )*
     */
    public java.lang.String queryTheOrg(java.lang.String sysName,java.lang.String oid) { 
        LOG.info("Executing operation queryTheOrg");
        System.out.println(sysName);
        System.out.println(oid);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.qycloud.taiyuan.ws.QueryInformationSvcPortType#updateUserPwd(java.lang.String  jsonStr )*
     */
    public java.lang.Boolean updateUserPwd(java.lang.String jsonStr) { 
        LOG.info("Executing operation updateUserPwd");
        System.out.println(jsonStr);
        try {
            java.lang.Boolean _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.qycloud.taiyuan.ws.QueryInformationSvcPortType#queryOrgs(java.lang.String  oid )*
     */
    public java.lang.String queryOrgs(java.lang.String oid) { 
        LOG.info("Executing operation queryOrgs");
        System.out.println(oid);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.qycloud.taiyuan.ws.QueryInformationSvcPortType#queryUsers(java.lang.String  oid )*
     */
    public java.lang.String queryUsers(java.lang.String oid) { 
        LOG.info("Executing operation queryUsers");
        System.out.println(oid);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.qycloud.taiyuan.ws.QueryInformationSvcPortType#queryTheUser(java.lang.String  sysName ,)java.lang.String  loginName )*
     */
    public java.lang.String queryTheUser(java.lang.String sysName,java.lang.String loginName) { 
        LOG.info("Executing operation queryTheUser");
        System.out.println(sysName);
        System.out.println(loginName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.qycloud.taiyuan.ws.QueryInformationSvcPortType#queryUsersBySysname(java.lang.String  sysName )*
     */
    public java.lang.String queryUsersBySysname(java.lang.String sysName) { 
        LOG.info("Executing operation queryUsersBySysname");
        System.out.println(sysName);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
